In [120]:
import numpy as np

In [121]:
a=np.array([1,2,3],dtype="int32")
print(a)

[1 2 3]


In [122]:
b=np.array([[9,0,8,0,7,0],[6,0,5,0,4,0]],dtype="int32")
print(b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]


In [123]:
#get dimensions 
a.ndim
b.ndim

2

In [124]:
b.shape

(2, 6)

In [125]:
a.dtype

dtype('int32')

In [126]:
a.itemsize*a.size
#or
a.nbytes

12

acessing chanings specific elments rows columns 

In [127]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [128]:
a[1,-2]

np.int64(13)

In [129]:
#get a specifice row
a[0:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [130]:
#get a specfic columnn
a[:,2]

array([ 3, 10])

In [131]:
#[start:end:step]
a[0,1:6:2]

array([2, 4, 6])

In [132]:
a[1,5]=20
print(a)

a[:,2]=[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [133]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [134]:
b[0,1,1]

np.int64(4)

In [135]:
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [136]:
np.zeros((2,3,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [137]:
np.ones([4,2,2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [138]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [139]:
b=np.full_like(a,4)
print(b)

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [140]:
#random
c=np.random.rand(4,2)
print(c)

[[0.68536973 0.29610508]
 [0.71737684 0.05857291]
 [0.01664303 0.79744557]
 [0.32693899 0.73234573]]


In [141]:
c=np.random.random_sample((4,2,3))
print(c)


[[[0.68836776 0.16156686 0.94078842]
  [0.2491433  0.53420692 0.5249543 ]]

 [[0.58212283 0.60905724 0.6987997 ]
  [0.15909258 0.91521175 0.274071  ]]

 [[0.95364305 0.88906913 0.21412608]
  [0.70004978 0.6236047  0.21719055]]

 [[0.04434836 0.69597595 0.78964236]
  [0.51481417 0.79659342 0.26554357]]]


In [142]:
np.random.randint(3,8,size=(3,3))

array([[6, 3, 4],
       [6, 5, 3],
       [6, 3, 3]], dtype=int32)

In [143]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [144]:
arr=np.full((5,5),1)
arr[1:4,1:4]=0
arr[2,2]=9
arr








array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [145]:
#### be carefull while copying 

a=np.array([1,2,3])
# b=a
# b[0]=100
# a
#do this instead
b=a.copy()
b[0]=100

a


array([1, 2, 3])

mathematics


In [146]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [147]:
a+2

array([3, 4, 5, 6])

In [148]:
a-2

array([-1,  0,  1,  2])

In [149]:
a*2

array([2, 4, 6, 8])

linear algebra

In [153]:
#linear algebra
a= np.ones((2,3))

b=np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [155]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

statistics


In [160]:
stats=np.array([[1,2,3],[4,5,6]])

In [163]:
np.min(stats)

np.int64(1)

In [169]:
np.max(stats,axis=0)

array([4, 5, 6])

reorganizing arrays


In [173]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [177]:
after=before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [180]:
#vertically stack
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

np.gen

In [183]:
filedata =np.genfromtxt('data.txt',delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

boolean masking and advanced indexing 